<a href="https://colab.research.google.com/github/danielarruda1000/geo_visao_comp/blob/main/GEO_VISAO_PROJ_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Questão 1**: Encontre o par de câmeras usando nessas imagens usando correspondência 3d 2d

**Questão 2**: faça a reconstrução 3d de um ponto (não usado na questão 1). Ou seja, vc vai definir um ponto em cada imagem e fazer a reconstrução do ponto 3d associado usando as câmeras

# Questão 1

In [ ]:
"""
Correspondências 3D - 2D


Foto 1:

(0,0,0) = 277, 537
(1,0,0) = 313, 487
(2,0,0) = 343, 444
(3,0,0) = 369, 407
(1,0,1) = 313, 444
(2,0,1) = 354, 407
(1,0,2) = 313, 400
(2,0,2) = 348, 352

Ponto de interesse (0,0,3) = 272, 390

Foto 2:

(0,0,0) = 188,598
(1,0,0) = 250, 575
(2,0,0) = 301, 552
(3,0,0) = 350, 532
(1,0,1) = 250, 540
(2,0,1) = 309, 517
(1,0,2) = 260, 497
(2,0,2) = 320, 474

Ponto de interesse (0,0,3) = 199, 470

"""

'\nCorrespondências 3D - 2D\n\n\nFoto 1:\n\n(0,0,0) = 277, 537 \n(1,0,0) = 313, 487\n(2,0,0) = 343, 444\n(3,0,0) = 369, 407\n(1,0,1) = 313, 444\n(2,0,1) = 354, 407\n(1,0,2) = 313, 400\n(2,0,2) = 348, 352\n\n\nFoto 2:\n\n(0,0,0) = 188,598\n(1,0,0) = 250, 575\n(2,0,0) = 301, 552\n(3,0,0) = 350, 532\n(1,0,1) = 250, 540\n(2,0,1) = 309, 517\n(1,0,2) = 260, 497\n(2,0,2) = 320, 474\n\n'

# Questão 1) Encontrar o par de cameras

In [2]:
import numpy as np

def achar_matriz_p_camera(points_3d, points_2d):

    n = points_3d.shape[0]
    A = []

    for i in range(n):
        X, Y, Z = points_3d[i]
        u, v = points_2d[i]

        A.append([ X, Y, Z, 1,   0, 0, 0, 0,   -u*X, -u*Y, -u*Z, -u ])
        A.append([ 0, 0, 0, 0,   X, Y, Z, 1,   -v*X, -v*Y, -v*Z, -v ])

    A = np.array(A)

    U, S, Vt = np.linalg.svd(A)
    P = Vt[-1].reshape(3, 4)

    return P / P[-1, -1]

In [3]:
# Pontos 3D
points_3d = np.array([
    (1,0,0),
    (2,0,0),
    (3,0,0),
    (1,0,1),
    (2,0,1),
    (1,0,2),

], dtype=float)

# Pontos 2D da foto 1
points_2d_foto_1 = np.array([
    (313,487),
    (343,444),
    (369,407),
    (313,444),
    (354,407),
    (313,400),
], dtype=float)

# Pontos 2D da foto 2
points_2d_foto_2 = np.array([
  (250, 575),
  (301, 552),
  (350, 532),
  (250, 540),
  (309, 517),
  (260, 497),
  (320, 474)
], dtype=float)

P1 = achar_matriz_p_camera(points_3d, points_2d_foto_1)
P2 = achar_matriz_p_camera(points_3d, points_2d_foto_2)

print("Matriz de câmera P1:", P1)
print()
print("Matrix de câmera P2:", P2)

Matriz de câmera P1: [[-7.54257974e+02 -1.49719217e+14 -3.74111447e+01  4.43930831e+02]
 [-6.95042004e+02 -7.27503050e+17 -2.65502357e+02  2.61902382e+02]
 [-1.85365854e+00 -9.89385834e+29 -5.30487805e-01  1.00000000e+00]]

Matrix de câmera P2: [[ 6.55162651e+01  3.52592439e+13 -5.44476857e+01  1.92712603e+02]
 [-1.14877197e+01 -1.10178192e+17 -1.41341971e+02  6.01768207e+02]
 [ 3.01886792e-02 -6.12299158e+29 -2.05660377e-01  1.00000000e+00]]


# Questão 2